# Generated by Django 4.2.13 on 2024-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medclass',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
