# Generated by Django 4.2.11 on 2024-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Munincipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('province', models.CharField(choices=[('PRI', 'Pinar del Río'), ('ART', 'Artemisa'), ('HAB', 'La Habana'), ('MAY', 'Mayabeque'), ('MTZ', 'Matanzas'), ('CFG', 'Cienfuegos'), ('VCL', 'Villa Clara'), ('SSP', 'Sancti Spíritus'), ('CAV', 'Ciego de Ávila'), ('CMG', 'Camagüey'), ('LTU', 'Las Tunas'), ('GRA', 'Granma'), ('HOL', 'Holguín'), ('SCU', 'Santiago'), ('GTM', 'Guantánamo'), ('IJV', 'Isla de la Juventud'), ('UNK', 'UNKNOWN')], default='UNK', max_length=3)),
            ],
        ),
    ]
