# Generated by Django 4.2.13 on 2024-06-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medclass_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='batch',
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinepresentation',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
