# Generated by Django 4.2.11 on 2024-05-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_munincipality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Munincipality',
            new_name='Municipality',
        ),
    ]
