# Generated by Django 4.2.11 on 2024-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='measurement_units',
            field=models.CharField(choices=[('mL', 'Milliliters'), ('oz', 'Ounce'), ('pt', 'Pint'), ('L', 'Liter'), ('mg', 'Milligram'), ('g', 'Gram'), ('lb', 'Pound'), ('-', 'Not Set')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='measurement',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
