# Generated by Django 4.2.13 on 2024-06-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_medicine_batch_medicine_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Donee',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='patient',
            new_name='donee',
        ),
    ]
