# Generated by Django 4.2.13 on 2024-07-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_patient_donee_rename_patient_treatment_donee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('-', 'Other or not set'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=1),
        ),
    ]
