# Generated by Django 4.2.13 on 2024-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='label',
            field=models.CharField(default='Sin Etiqueta', max_length=30),
        ),
    ]
