# Generated by Django 4.2.11 on 2024-04-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_note_phonenumber_contact_note_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='direction',
            new_name='address',
        ),
    ]
