# Generated by Django 4.2.11 on 2024-05-05 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_church_denomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='inscript',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 18, 28, 57, 409070, tzinfo=datetime.timezone.utc)),
        ),
    ]
