# Generated by Django 4.2.11 on 2024-04-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_direction_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
