# Generated by Django 4.2.13 on 2024-10-04 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_phonenumber_description_phonenumber_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='facilitator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_facilitator', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='church',
            name='priest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_priest', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'admin'), (1, 'colaborator'), (2, 'agent'), (3, 'priest'), (4, 'facilitator'), (5, 'donor')], default=5, null=True),
        ),
    ]
