# Generated by Django 4.2.13 on 2024-10-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_church_facilitator_alter_church_priest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
