# Generated by Django 4.2.11 on 2024-04-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_phonenumber_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact',
        ),
    ]
