# Generated by Django 4.2.13 on 2024-11-19 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_medicine_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receiver', models.CharField(blank=True, max_length=250, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.church')),
                ('dispatcher', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, default='unknown', max_length=60, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DispatchItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('stock', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donee')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['medicine', 'item']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispatch')),
            ],
            options={
                'verbose_name': 'Dispatch Item',
                'verbose_name_plural': 'Dispatch Items',
            },
        ),
    ]
