# Generated by Django 4.2.11 on 2024-05-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_disease_patient_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='core.medicine'),
        ),
    ]
