# Generated by Django 4.2.13 on 2024-11-21 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dispatch_item_alter_medicine_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatcher',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
