# Generated by Django 4.2.13 on 2024-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dispatch_date_alter_dispatch_dispatcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'verbose_name': 'Dispatch', 'verbose_name_plural': 'Dispatches'},
        ),
        migrations.AddField(
            model_name='dispatchitems',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
