# Generated by Django 4.2.11 on 2024-04-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_phonenumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
