# Generated by Django 4.2.11 on 2024-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_phonenumber_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
    ]
