# Generated by Django 4.2.13 on 2024-12-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_dispatch_options_dispatchitems_observation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(fields=('name', 'province'), name='unique_municipality_province'),
        ),
    ]
