# Generated by Django 4.2.13 on 2025-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='initial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
