# Generated by Django 4.2.13 on 2025-05-01 14:42

from django.db import migrations, models

def assign_codes(apps, schema_editor):
    Municipality = apps.get_model('core', 'Municipality')

    # Mapeo definido directamente en la migración (evita dependencias externas)
    PROVINCE_CODE_MAPPING = {
        'PRI': 1,
        'ART': 2,
        'HAB': 3,
        'MAY': 4,
        'MTZ': 5,
        'CFG': 6,
        'VCL': 7,
        'SSP': 8,
        'CAV': 9,
        'CMG': 10,
        'LTU': 11,
        'GRA': 12,
        'HOL': 13,
        'SCU': 14,
        'GTM': 15,
        'IJV': 16,
        'UNK': 17,
    }
    for mun in Municipality.objects.filter(code__isnull=True).iterator():
        mun.code = PROVINCE_CODE_MAPPING.get(mun.province, 17)
        mun.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(assign_codes),
    ]
