# Generated by Django 4.2.13 on 2025-05-01 15:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


def assign_codes(apps, schema_editor):
    Denomination = apps.get_model('core', 'Denomination')
    for idx, denom in enumerate(Denomination.objects.all().order_by('id'), start=1):
        if idx > 999:
            raise ValueError("¡Demasiados registros! El sistema solo soporta hasta 999 denominaciones")
        denom.code = idx
        denom.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_municipality_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código único de 3 dígitos (001-999)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.RunPython(
            assign_codes,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='denomination',
            name='code',
            field=models.PositiveSmallIntegerField(
                unique=True,
                blank=False,
                validators=[MinValueValidator(1), MaxValueValidator(999)],
                help_text="Código único de 3 dígitos (001-999)"
            ),
        ),
    ]
