# Generated by Django 4.2.13 on 2025-05-01 15:49

from django.db import migrations, models
from django.core.exceptions import ObjectDoesNotExist

def assign_codes(apps, schema_editor):
    Church = apps.get_model('core', 'Church')
    for church in Church.objects.filter(internal_code__isnull=True).select_related('denomination', 'municipality'):
        try:
            if church.denomination:  # Verifica que tenga denominación
                # Genera el código manualmente (más robusto que confiar solo en save())
                province_code = "000" if church.municipality is None else f"{church.municipality.code:03d}"
                denomination_code = f"{church.denomination.code:03d}"

                # Encuentra el último código para esta denominación
                last_code = Church.objects.filter(
                    denomination=church.denomination,
                    internal_code__isnull=False,
                    internal_code__startswith=f"{province_code}-{denomination_code}-"
                ).order_by('-internal_code').values_list('internal_code', flat=True).first()

                # Calcula el siguiente número
                last_sequence = int(last_code.split('-')[-1]) if last_code else 0
                next_sequence = last_sequence + 1

                # Asigna directamente el código
                church.internal_code = f"{province_code}-{denomination_code}-{next_sequence:03d}"
                church.save(update_fields=['internal_code'])
        except Exception as e:
            print(f"No se pudo generar código para iglesia ID {church.id}: {str(e)}")
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_denomination_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='internal_code',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Formato: [CódProvincia]-[CódDenominación]-[Secuencial] (ej: 013-003-002)',
                max_length=15,
                null=True,
                unique=True
            ),
        ),
        migrations.RunPython(
            assign_codes,
            reverse_code=migrations.RunPython.noop
        ),
    ]
