# Generated by Django 4.2.13 on 2025-05-23 01:36
from django.db import migrations, models
import django.core.validators

def clear_existing_codes(apps, schema_editor):
    """Establece todos los códigos existentes a NULL"""
    DoneeModel = apps.get_model('core', 'Donee')
    DoneeModel.objects.all().update(code=None)

def assign_new_codes(apps, schema_editor):
    """Asigna nuevos códigos secuenciales"""
    DoneeModel = apps.get_model('core', 'Donee')
    for idx, donee in enumerate(DoneeModel.objects.all().order_by('id'), start=1):
        if idx > 9999:
            raise ValueError("¡Demasiados registros! El sistema solo soporta hasta 9999 denominaciones")
        donee.code = idx
        donee.save(update_fields=['code'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_denomination_code'),
    ]

    operations = [
        # Primero: Quitar la restricción unique temporalmente
        migrations.AlterField(
            model_name='donee',
            name='code',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999)
                ]
            ),
        ),

        # Segundo: Limpiar los códigos existentes
        migrations.RunPython(
            clear_existing_codes,
            reverse_code=migrations.RunPython.noop
        ),

        # Tercero: Asignar nuevos códigos únicos
        migrations.RunPython(
            assign_new_codes,
            reverse_code=migrations.RunPython.noop
        ),

        # Cuarto: Finalmente establecer el campo como único
        migrations.AlterField(
            model_name='donee',
            name='code',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Código único de 4 dígitos (0001-9999)',
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999)
                ]
            ),
        ),
    ]
