# Generated by Django 4.2.13 on 2025-05-23 01:36

import django.core.validators
from django.db import migrations, models

def assign_codes(apps, schema_editor):
    DoneeModel = apps.get_model('core', 'Donee')
    for idx, donee in enumerate(DoneeModel.objects.all().order_by('id'), start=1):
        if idx > 9999:
            raise ValueError("¡Demasiados registros! El sistema solo soporta hasta 9999 denominaciones")
        donee.code = idx
        donee.save(update_fields=['code'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_denomination_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donee',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código único de 4 dígitos (0001-9999)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.RunPython(
            assign_codes,
            reverse_code=migrations.RunPython.noop
        ),
    ]
