# Generated by Django 4.2.13 on 2025-05-26 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_donee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donee',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código único de 3 dígitos (001-999)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
